/* docgen.c -- `cubc doc`, which turns /// comments into a reference.
 *
 * Only what is documented, plus the shape of everything else: a listing
 * that stays useful even when the comments have not been written yet.
 */
#include "cub.h"

static Buf out;
#define D(...) buf_printf(&out, __VA_ARGS__)

/* `int add(a: int, b: int)` -- how a reader would write the declaration. */
static char *signature(FnDecl *f) {
    Buf b;
    buf_init(&b);
    if (f->is_static) buf_puts(&b, "static ");
    buf_printf(&b, "%s %s(", ty_show(f->ret), f->name);
    for (int i = 0; i < f->params.len; i++) {
        VarSym *v = f->params.items[i];
        buf_printf(&b, "%s%s: %s", i ? ", " : "", v->name, ty_show(v->type));
    }
    buf_puts(&b, ")");
    return b.data;
}

/* Documentation is written as prose, so it goes through as written. */
static void prose(const char *doc, const char *indent) {
    if (!doc || !*doc) return;
    D("\n");
    const char *p = doc;
    while (*p) {
        const char *nl = strchr(p, '\n');
        int len = nl ? (int)(nl - p) : (int)strlen(p);
        D("%s%.*s\n", indent, len, p);
        if (!nl) break;
        p = nl + 1;
    }
}

/* A one-line summary for the table of contents: the first sentence. */
static char *summary(const char *doc) {
    if (!doc || !*doc) return cx_strdup("");
    const char *end = doc;
    while (*end && *end != '\n') {
        if (*end == '.' && (end[1] == ' ' || end[1] == '\n' || end[1] == 0)) { end++; break; }
        end++;
    }
    return cx_strndup(doc, (size_t)(end - doc));
}

static void fields_table(Vec *names, Vec *types, Vec *docs) {
    if (names->len == 0) { D("\nNo fields.\n"); return; }
    D("\n| Field | Type | |\n|---|---|---|\n");
    for (int i = 0; i < names->len; i++) {
        char *doc = (docs && i < docs->len) ? docs->items[i] : NULL;
        char *one = summary(doc);
        /* keep the table readable: newlines would break the row */
        for (char *c = one; *c; c++) if (*c == '\n') *c = ' ';
        D("| `%s` | `%s` | %s |\n", (char *)names->items[i],
          ty_show(types->items[i]), one);
    }
}

char *docgen_program(Program *p, const char *unit_name) {
    buf_init(&out);

    D("# %s\n", unit_name);
    D("\nGenerated by `cubc doc`.\n");

    /* ---- contents ---- */
    if (p->classes.len || p->structs.len || p->enums.len || p->fns.len) {
        D("\n## Contents\n\n");
        for (int i = 0; i < p->classes.len; i++)
            D("- class **%s**\n", ((ClassDef *)p->classes.items[i])->name);
        for (int i = 0; i < p->structs.len; i++)
            D("- struct **%s**\n", ((StructDef *)p->structs.items[i])->name);
        for (int i = 0; i < p->enums.len; i++)
            D("- enum **%s**\n", ((EnumDef *)p->enums.items[i])->name);
        for (int i = 0; i < p->fns.len; i++)
            D("- `%s`\n", signature(p->fns.items[i]));
    }

    /* ---- classes ---- */
    if (p->classes.len) D("\n---\n\n## Classes\n");
    for (int i = 0; i < p->classes.len; i++) {
        ClassDef *cd = p->classes.items[i];
        D("\n### `%s`", cd->name);
        if (cd->base_name) D(" — built on `%s`", cd->base_name);
        D("\n");
        prose(cd->doc, "");

        D("\n**Fields**\n");
        fields_table(&cd->fnames, &cd->ftypes, &cd->fdocs);

        int shown = 0;
        for (int j = 0; j < cd->statics.len + cd->methods.len; j++) {
            bool is_static = j < cd->statics.len;
            FnDecl *m = is_static ? cd->statics.items[j]
                                  : cd->methods.items[j - cd->statics.len];
            if (!shown++) D("\n**Methods**\n");
            D("\n#### `%s`\n", signature(m));
            prose(m->doc, "");
        }
        if (!shown) D("\nNo methods.\n");
    }

    /* ---- structs ---- */
    if (p->structs.len) D("\n---\n\n## Structs\n");
    for (int i = 0; i < p->structs.len; i++) {
        StructDef *sd = p->structs.items[i];
        D("\n### `%s`\n", sd->name);
        prose(sd->doc, "");
        fields_table(&sd->fnames, &sd->ftypes, &sd->fdocs);
    }

    /* ---- enums ---- */
    if (p->enums.len) D("\n---\n\n## Enums\n");
    for (int i = 0; i < p->enums.len; i++) {
        EnumDef *ed = p->enums.items[i];
        D("\n### `%s`\n", ed->name);
        prose(ed->doc, "");
        D("\nValues: ");
        for (int j = 0; j < ed->vals.len; j++)
            D("%s`%s.%s`", j ? ", " : "", ed->name, (char *)ed->vals.items[j]);
        D("\n");
    }

    /* ---- functions ---- */
    if (p->fns.len) D("\n---\n\n## Functions\n");
    for (int i = 0; i < p->fns.len; i++) {
        FnDecl *f = p->fns.items[i];
        D("\n### `%s`\n", signature(f));
        prose(f->doc, "");
    }

    /* ---- values ---- */
    if (p->globals.len) {
        D("\n---\n\n## Values\n\n");
        for (int i = 0; i < p->globals.len; i++) {
            Stmt *g = p->globals.items[i];
            D("- `%s %s: %s`\n", g->is_mut ? "var" : "let", g->name,
              ty_show(g->decl_type));
        }
    }

    return out.data;
}
